name = "hypo/helloworld"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'hypo/helloworld'"

[repository]
user = "hypo"
project = "helloworld"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"
